### ISSUE TITLE
Potential discrepancy in treatment of refunds.

### ISSUE THREAD

**Issue by jaypeedevlin** [clrcrl/advanced-sql#2]
In de15fb7, you changed this:

| task_id | inbound_payment_id | inbound_amount | payout_amount   | refund_amount |
|---------|--------------------|----------------|-----------------|---------------|
| 2       | 3                  | 30             | 0               | 30            |

to this:

| task_id | inbound_payment_id | inbound_amount | payout_amount   | refund_amount |
|---------|--------------------|----------------|-----------------|---------------|
| 2       | 3                  | 30             | 30               | 0            |

I _think_ this correction may have been in error, particularly when you compare how a full refund is treated in the final example (one row shown only):

| task_id | inbound_payment_id | inbound_amount | payout_amount   | refund_amount |
|---------|--------------------|----------------|-----------------|---------------|
| 5       | 13                 | 30             | 0               | 30            |

I have a solution that assumes the original is how it should be, but if the correction is _correct_, I don't really understand how refunds are meant to be represented given the inconsistency.

If my suspicion is correct, LMK and I can submit a PR to fix.

**Comment by clrcrl** [comment]
Ah, yes, I don't know what I was thinking 🤦‍♀️ 
Just pushed a commit to fix it!
